### ISSUE TITLE
Scripts to create the lexicon html file

### ISSUE THREAD

**Issue by williewillus** [VazkiiMods/BotaniaCD#5]
Can repurpose the existing lexicon site generator, but we'll want to do things like strip/replace the header and footers, remove the "this is bleeding edge" warning, etc.

Also, having actual recipes rendered would be nice.

**Comment by williewillus** [comment]
Just going to settle for a raw copy

**Comment by Alwinfy** [comment]
the wackos over in hexcasting have been working on "HexDoc" which is likely what you want.
